-- This is deprecated and probably will no longer work, or won't soon

CREATE TABLE songs (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(100) NOT NULL,
  artist VARCHAR(100) NOT NULL,
  album VARCHAR(100),
  length VARCHAR(10),
  PRIMARY KEY (id),
  CONSTRAINT UNIQUE (title, artist, album)
);

CREATE TABLE users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user CHAR(20) NOT NULL,
  date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  pass CHAR(60) NOT NULL,
  email VARCHAR(60) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT UNIQUE (user),
  CONSTRAINT UNIQUE (email)
);

CREATE TABLE plays (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  songid INT UNSIGNED NOT NULL,
  userid INT UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (songid) REFERENCES songs (id),
  FOREIGN KEY (userid) REFERENCES users (id)
);
