CREATE TABLE plays (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	artist VARCHAR(100),
	album VARCHAR(100),
	title VARCHAR(100),
	length VARCHAR(10),
	PRIMARY KEY (id)
);
